---
- name: Prepare environment
  hosts: local
  gather_facts: true

  roles:
    - role: geerlingguy.java

  tasks:
    - name: Ensure Android SDK global variables are placed in .zshrc
      ansible.builtin.blockinfile:
        path: '{{ ansible_env.HOME }}/.zshrc'
        block: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          export ANDROID_HOME=$HOME/Android/Sdk

  handlers:
    - name: Source .zshrc
      ansible.builtin.command:
        cmd: 'source {{ ansible_env.HOME }}/.zshrc'
